### ISSUE TITLE
Year picker

### ISSUE THREAD

**Issue by mholzi** [mholzi/Soundbeats#324]
Of course! Here is the updated, detailed walkthrough that allows users to both type the year directly into the text box and use the adjustment buttons.

### Description of the Target UI

This updated version enhances the year selection control panel. The UI will now function as follows:

* **An Editable Year Display**: The central text box will display the currently guessed year. Users can now click or tap on this box to type a year directly. Input is validated to ensure it's a 4-digit year within a reasonable range (e.g., 1950 to the current year).
* **Four Adjustment Buttons**: The `-10`, `-1`, `+1`, and `+10` buttons remain and function as before, providing an alternative way to adjust the year. They will instantly update the value in the editable text box.

This combination provides maximum flexibility, catering to users who prefer to type directly and those who prefer to make quick adjustments with buttons.

### Detailed Implementation Walkthrough

All changes will be made to the `custom_components/soundbeats/www/soundbeats-card.js` file.

#### Step 1: Locate and Update the Year Picker Function

First, you need to modify the `_renderYearPicker` function to remove the `readonly` attribute from the text input and add a new event handler for when a user types in it.

1.  Open the `soundbeats-card.js` file.
2.  Find the `_renderYearPicker` function.
3.  Replace it with the code below. The key changes are removing `readonly` and adding the `oninput` event handler to the `<input>` tag.

```javascript
_renderYearPicker(teamId, currentYear, selectedYear) {
    const minYear = 1950;
    return `
      <div class="year-picker-container">
        <input type="number"
               class="year-input"
               id="year-input-${teamId}"
               value="${selectedYear}"
               pattern="[0-9]*"
               oninput="this.getRootNode().host._handleYearInputChange('${teamId}', this.value)">
        <div class="year-buttons">
            <button class="year-button" onclick="this.getRootNode().host._adjustYear('${teamId}', -10)">-10</button>
            <button class="year-button" onclick="this.getRootNode().host._adjustYear('${teamId}', -1)">-1</button>
            <button class="year-button" onclick="this.getRootNode().host._adjustYear('${teamId}', 1)">+1</button>
            <button class="year-button" onclick="this.getRootNode().host._adjustYear('${teamId}', 10)">+10</button>
        </div>
      </div>
    `;
}
```

#### Step 2: Add the Functions to Handle Button Clicks and Direct Input

You will now have two functions: one for the buttons (`_adjustYear`) and a new one for handling typing in the text box (`_handleYearInputChange`). Add both of these functions to your `soundbeats-card.js` file, inside the `SoundbeatsCard` class.

```javascript
_adjustYear(teamId, adjustment) {
    const inputElement = this.shadowRoot.querySelector(`#year-input-${teamId}`);
    if (inputElement) {
        let currentValue = parseInt(inputElement.value, 10);
        currentValue += adjustment;

        // Add validation to keep the year within a reasonable range
        const minYear = 1950;
        const maxYear = new Date().getFullYear();
        if (currentValue < minYear) {
            currentValue = minYear;
        } else if (currentValue > maxYear) {
            currentValue = maxYear;
        }

        inputElement.value = currentValue;
        this.updateTeamYearGuess(teamId, currentValue);
    }
}

_handleYearInputChange(teamId, value) {
    // Validate that the input is a 4-digit number
    const year = parseInt(value, 10);
    const minYear = 1950;
    const maxYear = new Date().getFullYear();

    if (value.length === 4 && year >= minYear && year <= maxYear) {
        // Use a debounced call to update the state after the user stops typing
        this.debouncedServiceCall(`yearGuess_${teamId}`, () => {
            this.updateTeamYearGuess(teamId, year);
        }, 500); // 500ms delay
    }
}
```

**How these functions work together:**
* `_adjustYear`: This function is called by the buttons. It instantly changes the value in the text box and saves it to Home Assistant.
* `_handleYearInputChange`: This new function is called every time a user types in the text box. It checks if the input is a valid 4-digit year. To avoid sending updates on every keystroke, it uses `debouncedServiceCall` to wait until the user has paused typing for 500 milliseconds before saving the state. This provides a smooth user experience.

#### Step 3: Add/Update CSS for the New UI

The CSS from the previous walkthrough will work perfectly. If you haven't added it yet, place the following styles inside the `<style>` tag at the top of `soundbeats-card.js`. This will ensure the text box and buttons are styled correctly.

```css
.year-input {
  width: 100%;
  box-sizing: border-box;
  padding: 16px;
  margin-bottom: 12px;
  border: 1px solid var(--divider-color, #e0e0e0);
  border-radius: 8px;
  text-align: center;
  font-size: 2em;
  font-weight: bold;
  background-color: var(--secondary-background-color, #f5f5f5);
  color: var(--primary-text-color);
  /* For number inputs, hide the spinners on the side */
  -moz-appearance: textfield;
}

.year-input::-webkit-outer-spin-button,
.year-input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

.year-buttons {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 8px;
}

.year-button {
  padding: 16px;
  border: none;
  border-radius: 8px;
  background-color: var(--light-primary-color);
  color: var(--text-primary-color);
  font-size: 1.2em;
  font-weight: bold;
  cursor: pointer;
  transition: background-color 0.2s ease-in-out;
}

.year-button:hover {
  background-color: var(--primary-color);
}
```

After saving these changes, clear your browser's cache and reload your Home Assistant page. Your team card will now feature the fully interactive year input control.
