### ISSUE TITLE
Fixes Tablet view

### ISSUE THREAD

**Issue by mholzi** [mholzi/Soundbeats#338]
Of course. It looks like you're aiming for a more polished and dynamic tablet experience, which is an excellent goal for a party game. Based on the issues you've pointed out and the code provided, here is a detailed proposal to address the formatting, create an exciting team leaderboard, and clarify the timer's functionality.

### **1. Fixing the Layout and Formatting**

The core issue in your screenshot is that the main flexbox container for the two-panel layout isn't working as intended, and the team list is using mobile styles instead of the specific tablet styles.

**Concept:** Enforce a true two-panel layout that fills the screen, with the left panel for game action (timer/song) and the right for the live leaderboard.

**Detailed Implementation:**

This involves ensuring the CSS in `soundbeats-card.js` is correctly defined and applied. The `README.md` file already outlines this vision perfectly.

**A. HTML Structure (in `soundbeats-card.js`)**

Your `renderTabletMode()` function already has the correct structure. We just need to ensure the CSS targets it correctly.

```javascript
// From soundbeats-card.js
renderTabletMode() {
  // ...
  return `
    <div class="tablet-mode-container">
      <div class="tablet-left-panel">
        </div>
      <div class="tablet-right-panel">
        </div>
    </div>
  `;
}
```

**B. CSS Enhancements (in `soundbeats-card.js`)**

Let's propose CSS changes to fix the layout and add some polish.

```css
/* Add or modify these styles in soundbeats-card.js */

.tablet-mode-container {
  display: flex;
  /* Use min-height to ensure it fills the vertical screen */
  min-height: 100vh;
  background: linear-gradient(135deg, #4854a0 0%, #2c3e50 100%);
  color: white;
  padding: 1rem;
  gap: 1rem;
}

.tablet-left-panel, .tablet-right-panel {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  padding: 2rem;
  /* Add a subtle background to create panel separation */
  background: rgba(0, 0, 0, 0.15);
  border-radius: 20px;
  backdrop-filter: blur(10px);
}
```

This CSS will:
* Make the container truly full-height.
* Create two distinct, equal-width panels with a modern, glassy background.
* Center the content within each panel, providing a much cleaner structure.

---

### **2. Reimagining the Team Overview**

To make the team view "less boring," we can transform it from a static list into an animated, game-show-style leaderboard.

**Concept:** A live, animated leaderboard that clearly communicates rank, score, and round performance with exciting visual cues.

**Detailed Implementation:**

**A. Leaderboard Item Redesign**

Instead of the small vertical items, we'll use the larger horizontal layout defined in your tablet CSS and enhance it. Each team item will be a "row" in the leaderboard.

**Proposed HTML structure for each team item (generated by `renderOtherTeamsOverview`):**

```html
<div class="leaderboard-item rank-1">
  <div class="leaderboard-rank">
    <ha-icon icon="mdi:medal-gold"></ha-icon>
    <span>1st</span>
  </div>
  <div class="leaderboard-team-name">Team 5</div>
  <div class="leaderboard-points-update">+20</div>
  <div class="leaderboard-total-points">20 pts</div>
</div>
```

**B. CSS for the Animated Leaderboard**

Add this to the tablet-mode styles in `soundbeats-card.js`.

```css
.tablet-rankings-title {
  font-size: 2.5rem;
  font-weight: bold;
  text-shadow: 2px 2px 4px rgba(0,0,0,0.5);
  margin-bottom: 1rem;
}

.tablet-rankings-container {
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.leaderboard-item {
  display: flex;
  align-items: center;
  padding: 1.2rem;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 15px;
  transition: all 0.5s ease; /* For smooth re-ordering */
  border-left: 5px solid transparent;
}

/* Rank-based styling */
.leaderboard-item.rank-1 { border-left-color: #ffd700; background: rgba(255, 215, 0, 0.2); }
.leaderboard-item.rank-2 { border-left-color: #c0c0c0; background: rgba(192, 192, 192, 0.2); }
.leaderboard-item.rank-3 { border-left-color: #cd7f32; background: rgba(205, 127, 50, 0.2); }

.leaderboard-rank {
  font-size: 1.5rem;
  font-weight: bold;
  margin-right: 1rem;
  min-width: 80px;
}
.leaderboard-rank ha-icon { color: #ffd700; /* Will be changed based on rank */ }

.leaderboard-team-name {
  flex-grow: 1;
  font-size: 1.8rem;
}

.leaderboard-points-update {
  font-size: 1.2rem;
  font-weight: bold;
  color: #4caf50;
  padding: 0.5rem 1rem;
  background: rgba(76, 175, 80, 0.2);
  border-radius: 12px;
  margin-right: 1.5rem;
  opacity: 0;
  animation: fade-in-out 3s ease forwards;
}

.leaderboard-total-points {
  font-size: 2rem;
  font-weight: bold;
}

/* Animation for points gained in the last round */
@keyframes fade-in-out {
  0% { opacity: 0; transform: scale(0.5); }
  25% { opacity: 1; transform: scale(1.1); }
  80% { opacity: 1; transform: scale(1); }
  100% { opacity: 0; }
}
```

This implementation will give you:
* **Clear Ranks:** Gold, silver, and bronze styling for the top 3 teams.
* **Animated Point Updates:** A `+20` badge will pop up next to the team's name when they score and then fade away. This uses the `last_round_points` attribute from your team sensors.
* **Smooth Re-ordering:** When scores change, the list will animate smoothly instead of instantly re-arranging.

---

### **3. Adding the Countdown Timer**

Your analysis is correct—the timer should be visible on the left side during the guessing phase. The game logic is that the timer and the song *answer* are mutually exclusive. The timer runs while the song plays; the answer is shown after.

**Concept:** Make the countdown timer the central, high-energy focus of the left panel during the guessing phase.

**Detailed Implementation:**

Your `renderTabletMode()` function already contains the logic to show the timer only when the countdown is active. We just need to apply dramatic styling to make it a key feature.

**A. HTML Structure (in `soundbeats-card.js`)**

This structure is already in your code and is correct. We will just enhance its styling.

```javascript
// From renderTabletMode() in soundbeats-card.js
<div class="tablet-timer-section ${this.getCountdownCurrent() > 0 ? '' : 'hidden'}">
  <div class="tablet-countdown-timer">${this.getCountdownCurrent()}s</div>
  <div class="tablet-countdown-progress">
    <div class="tablet-countdown-progress-bar" style="width: ${this.getCountdownProgressPercent()}%"></div>
  </div>
</div>
```

**B. CSS for the High-Impact Timer**

```css
.tablet-timer-section {
  text-align: center;
}

.tablet-countdown-timer {
  font-size: 10rem; /* Make it massive */
  font-weight: bold;
  line-height: 1;
  color: #fff;
  text-shadow: 0 0 20px rgba(255, 255, 255, 0.7);
  /* Add pulse animation for the last few seconds */
  animation: pulse-timer 1s infinite;
  animation-play-state: paused; /* Will be started with JS */
}

/* Add a class for when the timer is low */
.tablet-countdown-timer.low-time {
  color: #ff6b6b; /* Red color for urgency */
  text-shadow: 0 0 20px #ff6b6b;
  animation-play-state: running;
}

@keyframes pulse-timer {
  0% { transform: scale(1); }
  50% { transform: scale(1.05); }
  100% { transform: scale(1); }
}

.tablet-countdown-progress {
  width: 80%;
  max-width: 400px;
  height: 20px;
  background: rgba(255, 255, 255, 0.2);
  border-radius: 10px;
  overflow: hidden;
  margin-top: 1rem;
}

.tablet-countdown-progress-bar {
  height: 100%;
  background: linear-gradient(90deg, #ffeb3b, #f39c12);
  transition: width 1s linear, background-color 0.5s ease;
  border-radius: 10px;
}
.tablet-countdown-progress-bar.low-time {
  background: linear-gradient(90deg, #ff6b6b, #f44336);
}
```

**C. JavaScript to Control Urgency Animation**

In your `updateDisplayValues()` or a similar function in `soundbeats-card.js`, add logic to apply the `low-time` class.

```javascript
// In soundbeats-card.js
updateCountdownDisplay() {
  //... existing code ...

  const timerElement = this.shadowRoot.querySelector('.tablet-countdown-timer');
  const progressBarElement = this.shadowRoot.querySelector('.tablet-countdown-progress-bar');
  const currentCountdown = this.getCountdownCurrent();

  if (timerElement && progressBarElement) {
    if (currentCountdown <= 5 && currentCountdown > 0) {
      timerElement.classList.add('low-time');
      progressBarElement.classList.add('low-time');
    } else {
      timerElement.classList.remove('low-time');
      progressBarElement.classList.remove('low-time');
    }
  }

  //... existing code ...
}
```

By implementing these detailed changes, you will create a far more engaging, polished, and professional-looking tablet view that directly addresses all the issues you raised.
